---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-snmp-exporter
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-snmp-exporter
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: snmp-exporter-mikrotik
    image:
      repository: quay.io/prometheus/snmp-exporter
    extraArgs:
      - "--config.file=/config/snmp.yaml"
    extraConfigmapMounts:
      - name: snmp-exporter-mikrotik
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: snmp-exporter-mikrotik
        readOnly: true
        defaultMode: 420
    serviceMonitor:
      enabled: true
      namespace: monitoring
      params:
        - name: mikrotik-rb3011
          target: 10.10.0.1
          module:
            - mikrotik
        - name: mikrotik-crs328
          target: 10.10.0.2
          module:
            - mikrotik
      path: /snmp
      scrapeTimeout: 10s
