---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki-simple-scalable
      version: 1.6.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    loki:
      structuredConfig:
        auth_enabled: false
        server:
          log_level: info
          http_listen_port: 3100
          grpc_listen_port: 9095
        memberlist:
          join_members: ["loki-memberlist"]
        limits_config:
          retention_period: 14d
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          max_cache_freshness_per_query: 10m
          split_queries_by_interval: 15m
          ingestion_rate_mb: 8
          ingestion_burst_size_mb: 16
        schema_config:
          configs:
            - from: "2022-01-11"
              store: boltdb-shipper
              object_store: s3
              schema: v12
              index:
                prefix: loki_index_
                period: 24h
        common:
          path_prefix: /var/loki
          replication_factor: 1
          storage:
            filesystem: null
            s3:
              endpoint: minio.minio:9000
              insecure: true
              bucketnames: loki-chunks
              access_key_id: "${MINIO_ACCESS_KEY}"
              secret_access_key: "${MINIO_SECRET_KEY}"
              s3forcepathstyle: true
          ring:
            kvstore:
              store: memberlist
        ruler:
          enable_api: true
          enable_alertmanager_v2: true
          alertmanager_url: http://kube-prometheus-stack-alertmanager.monitoring:9093
          storage:
            s3:
              bucketnames: loki-ruler
        compactor:
          working_directory: /var/loki/boltdb-shipper-compactor
          shared_store: s3
          compaction_interval: 10m
          retention_enabled: true
          retention_delete_delay: 2h
          retention_delete_worker_count: 150
        ingester:
          max_chunk_age: 1h
          max_transfer_retries: 0
          chunk_block_size: 262144
        analytics:
          reporting_enabled: false
    gateway:
      enabled: true
      replicas: 1
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "loki.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: loki-tls
            hosts:
              - *host
    write:
      replicas: 1
      persistence:
        size: 5Gi
        storageClass: openebs-zfspv-ssd
    read:
      replicas: 1
      persistence:
        size: 5Gi
        storageClass: openebs-zfspv-ssd
    monitoring:
      serviceMonitor:
        enabled: true
      # may add later
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
