---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homebridge
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: homebridge
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/oznu/homebridge
      tag: ubuntu-no-avahi@sha256:d173f3833349c4b68eef318e5169a9c7111e758b5fe96dfd03e9223d26fe6d52
    env:
      TZ: "America/New_York"
      PUID: 568
      PGID: 568
      HOMEBRIDGE_CONFIG_UI: 1
      HOMEBRIDGE_CONFIG_UI_PORT: 8581
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        ports:
          http:
            port: 8581
    persistence:
      config:
        enabled: true
        existingClaim: homebridge-config-v1
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: networking-internal-auth@kubernetescrd
        hosts:
          - host: "homebridge.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: homebridge-tls
            hosts:
              - "homebridge.${SECRET_DOMAIN}"
    config: |
      #!/bin/sh

      npm install homebridge-myq
      npm install homebridge-nest
      npm install homebridge-platform-orbit
