---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app homebridge
  namespace: home
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/oznu/homebridge
      tag: "2022-11-14"
    controller:
      strategy: RollingUpdate
    env:
      TZ: "${TZ}"
      ENABLE_AVAHI: "1"
    service:
      main:
        ports:
          http:
            port: &port 8581
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    persistence:
      homebridge:
        enabled: true
        existingClaim: homebridge-config
      startup-sh:
        enabled: true
        type: configMap
        name: &config homebridge-startup-sh
        mountPath: /homebridge/startup.sh
        subPath: startup.sh
        defaultMode: 493
    configMaps:
      config:
        enabled: true
        nameOverride: startup-sh
        data:
          startup.sh: |-
            #!/bin/sh
            npm install --save homebridge-dummy@latest
            npm install --save homebridge-myq@latest
            npm install --save homebridge-nest@latest
            npm install --save homebridge-orbit-irrigation@latest
            npm install --save homebridge-tplink-smarthome@latest
            npm install --save -g homebridge-camera-ui@latest
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "homebridge.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: homebridge-tls
            hosts:
              - *host
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /login
            port: *port
          initialDelaySeconds: 30
    podAnnotations:
      configmap.reloader.stakater.com/reload: *config
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi
