---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: promtail
      version: 3.8.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    config:
      lokiAddress: "http://loki:3100/loki/api/v1/push"
      snippets:
        extraScrapeConfigs: |
          - job_name: journal
            journal:
              path: /var/log/journal
              max_age: 12h
              labels:
                job: systemd-journal
            relabel_configs:
              - source_labels: ['__journal__systemd_unit']
                target_label: 'unit'
              - source_labels: ['__journal__hostname']
                target_label: 'hostname'
    defaultVolumes:
      - name: containers
        hostPath:
          path: /var/log/containers
      - name: pods
        hostPath:
          path: /var/log/pods
    defaultVolumeMounts:
      - name: containers
        mountPath: /var/log/containers
        readOnly: true
      - name: pods
        mountPath: /var/log/pods
        readOnly: true
    extraVolumes:
      - name: journal
        hostPath:
          path: /var/log/journal
      - name: ix
        hostPath:
          path: /mnt/k8s/ix-applications/docker/containers
    extraVolumeMounts:
      - name: journal
        mountPath: /var/log/journal
        readOnly: true
      - name: ix
        mountPath: /mnt/k8s/ix-applications/docker/containers
        readOnly: true
    serviceMonitor:
      enabled: true
