---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nginx
  namespace: networking
spec:
  groups:
    - name: nginx
      rules:
        - alert: NGINXAbsent
          annotations:
            description: NGINX component has dissapeared from Prometheus service discovery.
            summary: NGINX component has disappeared.
          expr: |
            absent(up{job=~".*nginx.*"} == 1)
          for: 10m
          labels:
            severity: critical
        - alert: NGINXConfigFailed
          annotations:
            description: bad ingress config - nginx config test failed
            summary: uninstall the latest ingress changes to allow config reloads to resume
          expr: |
            count(nginx_ingress_controller_config_last_reload_successful == 0) > 0
          for: 1s
          labels:
            severity: critical
        - alert: NGINXCertificateExpiry
          annotations:
            description: ssl certificate(s) will expire in less then a week
            summary: renew expiring certificates to avoid downtime
          expr: |
            (avg(nginx_ingress_controller_ssl_expire_time_seconds) by (host) - time()) < 604800
          for: 1s
          labels:
            severity: critical
        - alert: NGINXTooMany500s
          annotations:
            description: Too many 5XXs
            summary: More than 10% of all requests returned 5XX, this requires your attention
          expr: |
            sum(nginx_ingress_controller_requests{status=~"5.+"})
              /
            sum(nginx_ingress_controller_requests)
              > .10
          for: 1m
          labels:
            severity: warning
        - alert: NGINXTooMany400s
          annotations:
            description: Too many 4XXs
            summary: More than 10% of all requests returned 4XX, this requires your attention
          expr: |
            sum(nginx_ingress_controller_requests{status=~"4.+"})
              /
            sum(nginx_ingress_controller_requests)
              > .10
          for: 1m
          labels:
            severity: warning
