---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: thanos
      version: 10.5.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      registry: quay.io
      repository: thanos/thanos
      tag: v0.27.0
    query:
      enabled: true
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-sidecar
        sidecarsNamespace: monitoring
      ingress:
        enabled: true
        hostname: &host "thanos.${SECRET_DOMAIN}"
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        tls: true
        extraTls:
          - hosts:
              - *host
    existingObjstoreSecret: thanos-objstore
    queryFrontend:
      enabled: false
    bucketweb:
      enabled: true
    compactor:
      enabled: true
      persistence:
        enabled: false
    storegateway:
      enabled: true
      persistence:
        enabled: false
    ruler:
      enabled: true
      dnsDiscovery:
        enabled: true
      alertmanagers:
        - http://kube-prometheus-stack-alertmanager.monitoring:9093
      clusterName: home-ops
      extraFlags:
        - "--web.prefix-header=X-Forwarded-Prefix"
      config: |-
        groups:
          - name: "PrometheusWatcher"
            rules:
              - alert: "PrometheusDown"
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
      ingress:
        enabled: true
        hostname: &host "thanos-ruler.${SECRET_DOMAIN}"
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        tls: true
        extraTls:
          - hosts:
              - *host
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
