---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 5.6.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: blackbox-exporter
    nameOverride: blackbox-exporter
    allowIcmp: true
    secretConfig: false
    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            follow_redirects: true
            preferred_ip_protocol: "ip4"
        icmp:
          prober: icmp
          timeout: 30s
          icmp:
            preferred_ip_protocol: "ip4"
    serviceMonitor:
      enabled: true
      defaults:
        labels:
          release: prometheus
        interval: 30s
        scrapeTimeout: 30s
      targets:
        - name: router
          url: 10.10.0.1
          module: icmp
        - name: switch
          url: 10.10.0.2
          module: icmp
        - name: velop-mbr
          url: 10.10.0.5
          module: icmp
        - name: velop-fr
          url: 10.10.0.6
          module: icmp
        - name: nas-lan
          url: 10.10.0.10
          module: icmp
        - name: nas-ipmi
          url: 10.10.0.50
          module: icmp
        - name: garage-door
          url: 10.10.0.107
          module: icmp
        - name: hue-bridge
          url: 10.10.0.109
          module: icmp
        - name: hdhomerun
          url: 10.10.0.113
          module: icmp
        - name: eufy-br
          url: 10.10.0.120
          module: icmp
        - name: eufy-fr
          url: 10.10.0.121
          module: icmp
