---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: minio
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2023-12-23T07-19-11Z
    mode: standalone
    ignoreChartChecksums: false
    rootUser: "${MINIO_ROOT_USER}"
    rootPassword: "${MINIO_ROOT_PASSWORD}"
    drivesPerNode: 1
    replicas: 1
    persistence:
      enabled: true
      existingClaim: minio
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        # nginx.ingress.kubernetes.io/proxy-body-size: 250m
        nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      path: /
      hosts:
        - &host-api "s3.${SECRET_DOMAIN}"
      tls:
        - secretName: minio-api-tls
          hosts:
            - *host-api
    consoleIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
      path: /
      hosts:
        - &host-console "minio.${SECRET_DOMAIN}"
      tls:
        - secretName: minio-console-tls
          hosts:
            - *host-console
    users:
      - accessKey: "${MINIO_ACCESS_KEY}"
        secretKey: "${MINIO_SECRET_KEY}"
        policy: readwrite
    environment:
      TZ: "${TZ}"
      MINIO_UPDATE: "off"
      MINIO_PROMETHEUS_JOB_ID: "minio"
      MINIO_PROMETHEUS_URL: "http://thanos-query.monitoring:9090"
      MINIO_SERVER_URL: "https://s3.${SECRET_DOMAIN}"
    metrics:
      serviceMonitor:
        enabled: true
        includeNode: true
        public: true
    resources:
      requests:
        memory: 500Mi
        cpu: 100m
      limits:
        memory: 1000Mi
