---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: &app cloudflare-ddns
  namespace: networking
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 300
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: *app
              image: ghcr.io/onedr0p/kubernetes-kubectl:1.25.0@sha256:94ef8af361238220e5858fae7a55e9d3dfa6006f3fc74167cf5790ec921d3661
              envFrom:
                - secretRef:
                    name: cloudflare-creds
              command:
                - "/bin/bash"
                - &scriptPath "/app/cloudflare-ddns.sh"
              volumeMounts:
                - name: *app
                  mountPath: *scriptPath
                  subPath: &scriptName cloudflare-ddns.sh
                  readOnly: true
          volumes:
            - name: *app
              projected:
                defaultMode: 0755
                sources:
                  - configMap:
                      name: *app
                      items:
                        - key: *scriptName
                          path: *scriptName
