---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/fluxcd/flux2.git
  ref:
    # renovate: datasource=github-releases depName=fluxcd/flux2
    tag: v2.6.1
  ignore: |
    # exclude all
    /*
    # include manifest dir
    !/manifests
