---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: openebs-zfs-localpv
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/openebs/zfs-localpv.git
  ref:
    # renovate: registryUrl=https://openebs.github.io/zfs-localpv chart=zfs-localpv
    tag: zfs-localpv-2.8.0
  ignore: |
    # exclude all
    /*
    # include deploy crds dir
    !/deploy/helm/charts/crds
