---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-snmp-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-snmp-exporter
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
  values:
    extraArgs:
      - "--config.file=/config/snmp.yaml"
    extraConfigmapMounts:
      - name: snmp-exporter
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: snmp-exporter
        readOnly: true
        defaultMode: 420
    serviceMonitor:
      enabled: true
      namespace: monitoring
      selector:
        prometheus: prometheus
      params:
        - name: rb3011
          target: 10.10.0.1
          module:
            - mikrotik
      path: /snmp
      scrapeTimeout: 30s
