---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/miguelndecarvalho/speedtest-exporter
              tag: v3.5.4
            env:
              TZ: "${TZ}"
            resources:
              requests:
                cpu: 15m
                memory: 50M
              limits:
                memory: 100M
    service:
      main:
        ports:
          http:
            enabled: false
          metrics:
            enabled: true
            controller: main
            protocol: TCP
            port: 9798
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - interval: 60m
            path: /metrics
            port: metrics
            scrapeTimeout: 1m
