---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app network-ups-tools
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/jr0dd/network-ups-tools
              tag: v2.8.3@sha256:9f8e14d155c6ef05940cee6f8861e259e951eb11750aeddd02539d986dac1ca0
            env:
              TZ: "${TZ}"
            securityContext:
              privileged: true
          exporter:
            image:
              repository: ghcr.io/druggeri/nut_exporter
              tag: 3.2.0
    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${LB_NUT}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 3493
            protocol: TCP
      metrics:
        enabled: true
        controller: exporter
        ports:
          metrics:
            enabled: true
            port: 9199
            protocol: TCP
    serviceMonitor:
      main:
        enabled: true
        serviceName: network-ups-tools-metrics
        endpoints:
          - port: metrics
            scheme: http
            interval: 15s
            scrapeTimeout: 10s
            path: /ups_metrics
            params:
              target:
                - localhost:3493
            relabelings:
              - sourceLabels: [__param_target]
                targetLabel: target
    configMaps:
      config:
        enabled: true
        data:
          nut.conf: |-
            MODE=netserver
          upsd.conf: |-
            MAXAGE 20
            LISTEN 0.0.0.0
          upsd.users: |-
            [upsmon]
              password  = "${NUT_PASSWORD}"
              actions = SET
              instcmds = ALL
              upsmon primary
          ups.conf: |-
            [cyber-power]
              driver = usbhid-ups
              port = auto
              desc = "CyberPower CP1350PFCLCD"
              pollinterval = 10
          upsmon.conf: |-
            MONITOR cyber-power@localhost:3493 1 upsmon "${NUT_PASSWORD}" primary
            SHUTDOWNCMD "/sbin/shutdown -h +0"
            POWERDOWNFLAG /etc/killpower
            POLLFREQ 15
            POLLFREQALERT 5
            HOSTSYNC 15
    persistence:
      config:
        enabled: true
        type: configMap
        name: network-ups-tools-config
        globalMounts:
          - path: /etc/nut
            defaultMode: 256
      ups:
        enabled: true
        type: hostPath
        hostPath: /dev/bus/usb/003/003
        globalMounts:
          - path: /dev/bus/usb/001/001
            readOnly: false
