---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app network-ups-tools
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/jr0dd/network-ups-tools
      tag: v2.8.0@sha256:8878ab0f9420801f110ba1f173c97ad056cd9a6f56b181e1b39add1d91dc9626
    controller:
      strategy: RollingUpdate
    env:
      TZ: "${TZ}"
    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${LB_NUT}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 3493
            protocol: TCP
      metrics:
        enabled: true
        ports:
          metrics:
            enabled: true
            port: 9199
            protocol: TCP
    serviceMonitor:
      main:
        enabled: true
        serviceName: network-ups-tools-metrics
        endpoints:
          - port: metrics
            scheme: http
            interval: 15s
            scrapeTimeout: 10s
            path: /ups_metrics
            params:
              target:
                - localhost:3493
            relabelings:
              - sourceLabels: [__param_target]
                targetLabel: target
    securityContext:
      privileged: true
    persistence:
      config:
        enabled: true
        type: configMap
        name: &config network-ups-tools-config
        mountPath: /etc/nut
        defaultMode: 256
      ups:
        enabled: true
        type: hostPath
        hostPath: /dev/bus/usb/003/003
        mountPath: /dev/bus/usb/001/001
        readOnly: false
    configMaps:
      config:
        enabled: true
        data:
          nut.conf: |-
            MODE=netserver
          upsd.conf: |-
            MAXAGE 20
            LISTEN 0.0.0.0
          upsd.users: |-
            [upsmon]
              password  = "${NUT_PASSWORD}"
              actions = SET
              instcmds = ALL
              upsmon primary
          ups.conf: |-
            [cyber-power]
              driver = usbhid-ups
              port = auto
              desc = "CyberPower CP1350PFCLCD"
              pollinterval = 10
          upsmon.conf: |-
            MONITOR cyber-power@localhost:3493 1 upsmon "${NUT_PASSWORD}" primary
            SHUTDOWNCMD "/sbin/shutdown -h +0"
            POWERDOWNFLAG /etc/killpower
            POLLFREQ 15
            POLLFREQALERT 5
            HOSTSYNC 15
    podAnnotations:
      configmap.reloader.stakater.com/reload: *config
    additionalContainers:
      exporter:
        name: exporter
        image: ghcr.io/druggeri/nut_exporter:3.1.1
