---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app network-ups-tools
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    controller:
      strategy: RollingUpdate
    image:
      repository: ghcr.io/k8s-at-home/network-ups-tools
      tag: v2.7.4-2479-g86a32237@sha256:cbd5d4cc12454121ee9cd3587053c4de313575ee367ffcad07b2fc92a1e8be8c
    env:
      TZ: "${TZ}"
    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${LB_NUT}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 3493
            protocol: TCP
      metrics:
        enabled: true
        ports:
          metrics:
            enabled: true
            port: 9199
            protocol: TCP
    securityContext:
      privileged: true
    persistence:
      config:
        enabled: true
        type: configMap
        name: &config network-ups-tools-config
        mountPath: /etc/nut
        defaultMode: 256
      ups:
        enabled: true
        type: hostPath
        hostPath: /dev/bus/usb/003/003
        mountPath: /dev/bus/usb/001/001
        readOnly: false
    configmap:
      config:
        enabled: true
        data:
          nut.conf: |-
            MODE=netserver
          upsd.conf: |-
            MAXAGE 20
            LISTEN 0.0.0.0
          upsd.users: |-
            [upsmon]
              password  = "${NUT_PASSWORD}"
              actions = SET
              instcmds = ALL
              upsmon primary
          ups.conf: |-
            [cyber-power]
              driver = usbhid-ups
              port = auto
              desc = "CyberPower CP1350PFCLCD"
              pollinterval = 10
          upsmon.conf: |-
            MONITOR cyber-power@localhost:3493 1 upsmon "${NUT_PASSWORD}" primary
            SHUTDOWNCMD "/sbin/shutdown -h +0"
            POWERDOWNFLAG /etc/killpower
            POLLFREQ 15
            POLLFREQALERT 5
            HOSTSYNC 15
    podAnnotations:
      configmap.reloader.stakater.com/reload: *config
    additionalContainers:
      exporter:
        name: nut-exporter
        image:
          repository: ghcr.io/druggeri/nut_exporter
          tag: 2.4.1@sha256:7b7b3f035ba064ae69cf571cfbb8632a9b783f9b739e12244ddcce34b3606d43
