---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app blocky
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.22
    controller:
      strategy: RollingUpdate
    env:
      TZ: "${TZ}"
    service:
      main:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: *app
          metallb.universe.tf/loadBalancerIPs: &lb "${LB_BLOCKY}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 4000
            protocol: TCP
      dns:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: *app
          metallb.universe.tf/loadBalancerIPs: *lb
        externalTrafficPolicy: Local
        ports:
          tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
    serviceMonitor:
      main:
        enabled: true
        serviceName: *app
        endpoints:
          - interval: 30s
            path: /metrics
            port: http
            scrapeTimeout: 10s
    persistence:
      config:
        enabled: true
        type: configMap
        name: &config blocky-config
        mountPath: /app/config.yml
        subPath: config.yml
    configMaps:
      config:
        enabled: true
        data:
          config.yml: |-
            upstream:
              default:
                - tcp-tls:one.one.one.one:853
                - tcp-tls:dns.quad9.net:853
            conditional:
              mapping:
                ${SECRET_DOMAIN}: ${LB_K8S_GATEWAY}
            clientLookup:
              upstream: ${GATEWAY_IP}
            bootstrapDns: tcp+udp:1.1.1.1
            blocking:
              blackLists:
                ads:
                  - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
                fakenews:
                  - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
              whiteLists:
                ads:
                  - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
                  - |
                    investing.com
              clientGroupsBlock:
                default:
                  - ads
                  - fakenews
            prometheus:
              enable: true
              path: /metrics
            httpPort: 4000
            logLevel: info
    podAnnotations:
      configmap.reloader.stakater.com/reload: *config
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 150Mi
