---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-agent
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: vector
      version: 0.17.0
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: vector-aggregator
  values:
    image:
      repository: timberio/vector
      tag: 0.25.1-debian
    role: Agent
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: false
      sources:
        journal_logs:
          type: journald
          journal_directory: /var/log/journal
        kubernetes_logs:
          type: kubernetes_logs
          pod_annotation_fields:
            container_image: "container_image"
            container_name: "container_name"
            pod_annotations: "pod_annotations"
            pod_labels: "pod_labels"
            pod_name: "pod_name"
        vector_metrics:
          type: internal_metrics
      sinks:
        loki_journal:
          type: vector
          inputs:
            - journal_logs
          address: vector-aggregator:6000
          version: "2"
        loki_kubernetes:
          type: vector
          inputs:
            - kubernetes_logs
          address: vector-aggregator:6010
          version: "2"
        prom_exporter:
          type: prometheus_exporter
          inputs:
            - vector_metrics
          address: 0.0.0.0:9090
    service:
      enabled: false
    podMonitor:
      enabled: true
    securityContext:
      privileged: true
    tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
