---
- name: zed | install zed packages
  ansible.builtin.apt:
    update_cache: yes # yamllint disable-line rule:truthy
    pkg:
      - zfs-zed
    state: present

- name: zed | configure zed service
  ansible.builtin.template:
    src: zed.rc.j2
    dest: /etc/zfs/zed.d/zed.rc
    mode: 0600

- name: zed | restart zed service
  ansible.builtin.systemd:
    name: zfs-zed
    daemon_reload: true
    enabled: true
    state: restarted
