---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: discord-ghcr-io
  namespace: flux-system
spec:
  image: ghcr.io/jr0dd/discord-bot-react-frontend
  interval: 1h
  secretRef:
    name: ghcr-io-creds
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: discord-ghcr-io
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: discord-ghcr-io
  policy:
    semver:
      range: ">=0.1.0"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: discord-ghcr-io
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: home-ops
  interval: 1h
  update:
    path: ./cluster/apps/discord
    strategy: Setters
  git:
    checkout:
      ref:
        branch: main
    push:
      branch: main
    commit:
      author:
        name: wyoa-bot
        email: wyoa-bot[bot]@users.noreply.github.com
      messageTemplate: |
        fix(container): update {{range .Updated.Images}}{{println .}}{{end}}
