---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: prowlarr
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/k8s-at-home/prowlarr
      tag: v0.4.0.1802@sha256:6a49e194e0e3d2c9604ac8eecfddc00ff059d33909a3bc91bb6dbf2174f33686
    env:
      TZ: "${TZ}"
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/prowlarr/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: &host "prowlarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: prowlarr-tls
            hosts:
              - *host
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 500Mi
