---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app puppeteer
  namespace: discord
spec:
  interval: 10m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    controller:
      strategy: RollingUpdate
    image:
      repository: ghcr.io/jr0dd/puppeteer
      tag: v15.3.1@sha256:858e4e95fbafcb7e926b8cd98782aa666239e55e403c34525628a2c470c4b5a1
      pullPolicy: Always
    command:
      - node
      - server.js
    args:
      - '--disable-gpu'
      - '--disable-software-rasterizer'
      - '--no-zygote'
      - '--disable-features=IsolateOrigins,site-per-process'
      - '--disable-site-isolation-trials'
      - '--disable-web-security'
      - '--remote-debugging-port=4000'
    env:
      TZ: "${TZ}"
    service:
      main:
        ports:
          http:
            port: &port 4000
    persistence:
      config:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "puppeteer.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: puppeteer-tls
            hosts:
              - *host
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /json/list
            port: *port
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi
