---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: qbittorrent-exporter
  namespace: media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
  podMetricsEndpoints:
    - interval: 15s
      path: /metrics
      port: metrics
      scrapeTimeout: 5s
      relabelings:
        - sourceLabels: ['__namespace__', 'job']
          regex: ".+/(.*)"
          targetLabel: "job"
          replacement: "$1"
