---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: reloader
      version: v1.0.24
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    reloader:
      podMonitor:
        enabled: true
    resources:
      requests:
        cpu: 15m
        memory: 184M
      limits:
        memory: 184M
