---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app discord-stock-ticker
  namespace: discord
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/jr0dd/discord-stock-ticker
              tag: v3.10.8@sha256:4dc38fc3cff2f1e88c9179000d9355b22d4438a39819efa8504f077b1a9f6da7
            env:
              TZ: "${TZ}"
            envFrom:
              - secretRef:
                  name: discord-tokens
            lifecycle:
              postStart:
                exec:
                  command: ["bash", "/config/payload.sh"]
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 200Mi
    service:
      main:
        ports:
          http:
            port: 8080
    serviceMonitor:
      main:
        enabled: true
        serviceName: *app
        endpoints:
          - interval: 30s
            path: /metrics
            port: http
            scrapeTimeout: 10s
    persistence:
      config:
        enabled: true
        type: configMap
        name: payload-config
        globalMounts:
          - path: /config/payload.sh
            subPath: payload.sh
            defaultMode: 493
