---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app kopia
  namespace: storage
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    initContainers:
      wait-for-repo:
        image: ghcr.io/onedr0p/kopia:0.12.1@sha256:dfe496c5ab894bb5d6084150e7fc0a31c9d4d6472c2c9ea1e2e14ffee60d6d93
        command:
          - /bin/bash
          - -c
          - |-
            until [ -f /snapshots/kopia.repository.f ]; do
                printf "\e[1;32m%-6s\e[m\n" "Awaiting for the Kopia repo to become ready ..."
                sleep 1
            done
        volumeMounts:
          - name: snapshots
            mountPath: /snapshots
    image:
      repository: ghcr.io/onedr0p/kopia
      tag: 0.12.1@sha256:dfe496c5ab894bb5d6084150e7fc0a31c9d4d6472c2c9ea1e2e14ffee60d6d93
    env:
      TZ: "${TZ}"
      KOPIA_PASSWORD: "none"
    command: kopia
    args:
      - server
      - --insecure
      - --address
      - 0.0.0.0:80
      - --metrics-listen-addr
      - 0.0.0.0:8080
      - --without-password
    service:
      main:
        ports:
          http:
            port: 80
          metrics:
            enabled: true
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "kopia.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: kopia-tls
            hosts:
              - *host
    podSecurityContext:
      supplementalGroups:
        - 1042
    persistence:
      config:
        enabled: true
        type: configMap
        name: *app
        subPath: repository.config
        mountPath: /config/repository.config
        readOnly: true
      snapshots:
        enabled: true
        type: pvc
        existingClaim: snapshots
        mountPath: /snapshots
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 250Mi
