---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app kopia
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          wait-for-repo:
            image: ghcr.io/onedr0p/kopia:0.13.0@sha256:ee6608635237c9ddf3ec5b456122cb60f0195c5cad84b06e945498f2338bff59
            command:
              - /bin/bash
              - -c
              - |-
                until [ -f /snapshots/kopia.repository.f ]; do
                    printf "\e[1;32m%-6s\e[m\n" "Awaiting for the Kopia repo to become ready ..."
                    sleep 1
                done
            volumeMounts:
              - name: snapshots
                mountPath: /snapshots
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/kopia
              tag: 0.13.0@sha256:ee6608635237c9ddf3ec5b456122cb60f0195c5cad84b06e945498f2338bff59
            env:
              TZ: "${TZ}"
              KOPIA_PASSWORD: "none"
            args:
              - server
              - start
              - --insecure
              - --address
              - 0.0.0.0:80
              - --metrics-listen-addr
              - 0.0.0.0:8080
              - --without-password
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 80
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              privileged: true
              runAsUser: 0
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 250Mi
    service:
      main:
        ports:
          http:
            port: 80
          metrics:
            enabled: true
            controller: main
            port: 8080
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
        hosts:
          - host: &host "kopia.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - secretName: kopia-tls
            hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: secret
        name: kopia-repository-secret
        globalMounts:
          - path: /app/config/repository.config
            subPath: repository.config
            readOnly: true
      cache:
        type: emptyDir
        globalMounts:
          - path: /app/cache
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/logs
      snapshots:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: snapshots
        globalMounts:
          - path: /snapshots
