---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zfs-localpv
  namespace: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: zfs-localpv
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: openebs-zfs-localpv
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    crd:
      enableInstall: false
