---
name: Cloudflare Proxied Networks Update

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  CLOUDFLARE_PROXIED_NETWORKS_FILE: >-
    cluster/apps/networking/ingress-nginx/cloudflare-proxied-networks.txt
jobs:
  update:
    name: Update
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Cloudflare Proxied Networks
        run: |
          bash ./.github/scripts/cloudflare-proxied-networks.sh > ${{ env.CLOUDFLARE_PROXIED_NETWORKS_FILE }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: github-action/update-cloudflare-proxied-networks
          delete-branch: true
          title: "chore(github-action): update cloudflare proxied networks"
          signoff: true
          commit-message: "chore(github-action): update cloudflare proxied networks"
          body: |
            Update cloudflare proxy networks configmap from https://www.cloudflare.com/ips/
          labels: |
            renovate/github-action
