---
name: Labels

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

jobs:
  labels:
    name: Labels
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Generate Size
        uses: pascalgn/size-label-action@v0.5.5
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          sizes: >
            {
              "0": "XS",
              "20": "S",
              "50": "M",
              "200": "L",
              "800": "XL",
              "2000": "XXL"
            }

      - name: Generate Labels
        uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yaml
          repo-token: ${{ steps.generate-token.outputs.token }}

      - name: Sync Labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yaml
          token: ${{ steps.generate-token.outputs.token }}
